/* Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: MIT
 */

/* The parts of the libibverbs ABI that ibv-core.h mirrors, which
 * test-ibv-layout.cpp checks against <infiniband/verbs.h>. The list is
 * in the order ibv-core.h declares them; add an entry here when you add
 * a type, member, or constant there.
 *
 * Each file that includes this one defines the macros first:
 *
 *   HIPOBJ_IBV_TYPE(type)            A struct's or union's size and
 *                                    alignment
 *   HIPOBJ_IBV_MEMBER(type, member)  A member's offset and size. A
 *                                    nested member is named with dots,
 *                                    as in offsetof().
 *   HIPOBJ_IBV_VALUE(name)           An enumerator's or macro's value
 *
 * This file is included once per list, so it has no include guard.
 *
 * Some things in ibv-core.h aren't in the list, since rdma-core names them
 * differently:
 *
 * - The type of ibv_device's _ops member, which rdma-core names
 *   _ibv_device_ops, and the types of ibv_send_wr's bind_mw and tso
 *   members, which rdma-core leaves unnamed. They're checked as the
 *   members.
 * - IBV_ACCESS_OPTIONAL_LAST, which rdma-core names
 *   IB_UVERBS_ACCESS_OPTIONAL_LAST. ibv-core.h only uses it to define
 *   IBV_ACCESS_OPTIONAL_RANGE, which is checked.
 */

HIPOBJ_IBV_VALUE(IB_UVERBS_ACCESS_LOCAL_WRITE)
HIPOBJ_IBV_VALUE(IB_UVERBS_ACCESS_REMOTE_WRITE)
HIPOBJ_IBV_VALUE(IB_UVERBS_ACCESS_REMOTE_READ)
HIPOBJ_IBV_VALUE(IB_UVERBS_ACCESS_REMOTE_ATOMIC)
HIPOBJ_IBV_VALUE(IB_UVERBS_ACCESS_MW_BIND)
HIPOBJ_IBV_VALUE(IB_UVERBS_ACCESS_ZERO_BASED)
HIPOBJ_IBV_VALUE(IB_UVERBS_ACCESS_ON_DEMAND)
HIPOBJ_IBV_VALUE(IB_UVERBS_ACCESS_HUGETLB)
HIPOBJ_IBV_VALUE(IB_UVERBS_ACCESS_FLUSH_GLOBAL)
HIPOBJ_IBV_VALUE(IB_UVERBS_ACCESS_FLUSH_PERSISTENT)
HIPOBJ_IBV_VALUE(IB_UVERBS_ACCESS_RELAXED_ORDERING)

HIPOBJ_IBV_VALUE(IBV_ACCESS_OPTIONAL_FIRST)
HIPOBJ_IBV_VALUE(IBV_ACCESS_OPTIONAL_RANGE)

HIPOBJ_IBV_TYPE(union ibv_gid)
HIPOBJ_IBV_MEMBER(union ibv_gid, raw)
HIPOBJ_IBV_MEMBER(union ibv_gid, global)
HIPOBJ_IBV_MEMBER(union ibv_gid, global.subnet_prefix)
HIPOBJ_IBV_MEMBER(union ibv_gid, global.interface_id)

HIPOBJ_IBV_VALUE(IBV_GID_TYPE_IB)
HIPOBJ_IBV_VALUE(IBV_GID_TYPE_ROCE_V1)
HIPOBJ_IBV_VALUE(IBV_GID_TYPE_ROCE_V2)

HIPOBJ_IBV_TYPE(struct ibv_gid_entry)
HIPOBJ_IBV_MEMBER(struct ibv_gid_entry, gid)
HIPOBJ_IBV_MEMBER(struct ibv_gid_entry, gid_index)
HIPOBJ_IBV_MEMBER(struct ibv_gid_entry, port_num)
HIPOBJ_IBV_MEMBER(struct ibv_gid_entry, gid_type)
HIPOBJ_IBV_MEMBER(struct ibv_gid_entry, ndev_ifindex)

HIPOBJ_IBV_VALUE(IBV_NODE_UNKNOWN)
HIPOBJ_IBV_VALUE(IBV_NODE_CA)
HIPOBJ_IBV_VALUE(IBV_NODE_SWITCH)
HIPOBJ_IBV_VALUE(IBV_NODE_ROUTER)
HIPOBJ_IBV_VALUE(IBV_NODE_RNIC)
HIPOBJ_IBV_VALUE(IBV_NODE_USNIC)
HIPOBJ_IBV_VALUE(IBV_NODE_USNIC_UDP)
HIPOBJ_IBV_VALUE(IBV_NODE_UNSPECIFIED)

HIPOBJ_IBV_VALUE(IBV_TRANSPORT_UNKNOWN)
HIPOBJ_IBV_VALUE(IBV_TRANSPORT_IB)
HIPOBJ_IBV_VALUE(IBV_TRANSPORT_IWARP)
HIPOBJ_IBV_VALUE(IBV_TRANSPORT_USNIC)
HIPOBJ_IBV_VALUE(IBV_TRANSPORT_USNIC_UDP)
HIPOBJ_IBV_VALUE(IBV_TRANSPORT_UNSPECIFIED)

HIPOBJ_IBV_VALUE(IBV_ATOMIC_NONE)
HIPOBJ_IBV_VALUE(IBV_ATOMIC_HCA)
HIPOBJ_IBV_VALUE(IBV_ATOMIC_GLOB)

HIPOBJ_IBV_TYPE(struct ibv_device_attr)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, fw_ver)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, node_guid)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, sys_image_guid)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_mr_size)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, page_size_cap)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, vendor_id)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, vendor_part_id)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, hw_ver)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_qp)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_qp_wr)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, device_cap_flags)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_sge)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_sge_rd)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_cq)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_cqe)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_mr)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_pd)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_qp_rd_atom)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_ee_rd_atom)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_res_rd_atom)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_qp_init_rd_atom)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_ee_init_rd_atom)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, atomic_cap)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_ee)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_rdd)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_mw)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_raw_ipv6_qp)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_raw_ethy_qp)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_mcast_grp)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_mcast_qp_attach)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_total_mcast_qp_attach)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_ah)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_fmr)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_map_per_fmr)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_srq)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_srq_wr)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_srq_sge)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, max_pkeys)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, local_ca_ack_delay)
HIPOBJ_IBV_MEMBER(struct ibv_device_attr, phys_port_cnt)

HIPOBJ_IBV_VALUE(IBV_MTU_256)
HIPOBJ_IBV_VALUE(IBV_MTU_512)
HIPOBJ_IBV_VALUE(IBV_MTU_1024)
HIPOBJ_IBV_VALUE(IBV_MTU_2048)
HIPOBJ_IBV_VALUE(IBV_MTU_4096)

HIPOBJ_IBV_VALUE(IBV_PORT_NOP)
HIPOBJ_IBV_VALUE(IBV_PORT_DOWN)
HIPOBJ_IBV_VALUE(IBV_PORT_INIT)
HIPOBJ_IBV_VALUE(IBV_PORT_ARMED)
HIPOBJ_IBV_VALUE(IBV_PORT_ACTIVE)
HIPOBJ_IBV_VALUE(IBV_PORT_ACTIVE_DEFER)

HIPOBJ_IBV_VALUE(IBV_LINK_LAYER_UNSPECIFIED)
HIPOBJ_IBV_VALUE(IBV_LINK_LAYER_INFINIBAND)
HIPOBJ_IBV_VALUE(IBV_LINK_LAYER_ETHERNET)

HIPOBJ_IBV_TYPE(struct ibv_port_attr)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, state)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, max_mtu)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, active_mtu)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, gid_tbl_len)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, port_cap_flags)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, max_msg_sz)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, bad_pkey_cntr)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, qkey_viol_cntr)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, pkey_tbl_len)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, lid)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, sm_lid)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, lmc)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, max_vl_num)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, sm_sl)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, subnet_timeout)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, init_type_reply)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, active_width)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, active_speed)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, phys_state)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, link_layer)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, flags)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, port_cap_flags2)
HIPOBJ_IBV_MEMBER(struct ibv_port_attr, active_speed_ex)

HIPOBJ_IBV_VALUE(IBV_WC_GRH)
HIPOBJ_IBV_VALUE(IBV_WC_WITH_IMM)
HIPOBJ_IBV_VALUE(IBV_WC_IP_CSUM_OK)
HIPOBJ_IBV_VALUE(IBV_WC_WITH_INV)
HIPOBJ_IBV_VALUE(IBV_WC_TM_SYNC_REQ)
HIPOBJ_IBV_VALUE(IBV_WC_TM_MATCH)
HIPOBJ_IBV_VALUE(IBV_WC_TM_DATA_VALID)

HIPOBJ_IBV_VALUE(IBV_WC_SEND)
HIPOBJ_IBV_VALUE(IBV_WC_RDMA_WRITE)
HIPOBJ_IBV_VALUE(IBV_WC_RDMA_READ)
HIPOBJ_IBV_VALUE(IBV_WC_COMP_SWAP)
HIPOBJ_IBV_VALUE(IBV_WC_FETCH_ADD)
HIPOBJ_IBV_VALUE(IBV_WC_BIND_MW)
HIPOBJ_IBV_VALUE(IBV_WC_LOCAL_INV)
HIPOBJ_IBV_VALUE(IBV_WC_TSO)
HIPOBJ_IBV_VALUE(IBV_WC_FLUSH)
HIPOBJ_IBV_VALUE(IBV_WC_ATOMIC_WRITE)
HIPOBJ_IBV_VALUE(IBV_WC_RECV)
HIPOBJ_IBV_VALUE(IBV_WC_RECV_RDMA_WITH_IMM)

HIPOBJ_IBV_VALUE(IBV_WC_SUCCESS)
HIPOBJ_IBV_VALUE(IBV_WC_LOC_LEN_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_LOC_QP_OP_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_LOC_EEC_OP_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_LOC_PROT_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_WR_FLUSH_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_MW_BIND_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_BAD_RESP_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_LOC_ACCESS_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_REM_INV_REQ_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_REM_ACCESS_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_REM_OP_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_RETRY_EXC_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_RNR_RETRY_EXC_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_LOC_RDD_VIOL_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_REM_INV_RD_REQ_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_REM_ABORT_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_INV_EECN_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_INV_EEC_STATE_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_FATAL_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_RESP_TIMEOUT_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_GENERAL_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_TM_ERR)
HIPOBJ_IBV_VALUE(IBV_WC_TM_RNDV_INCOMPLETE)

HIPOBJ_IBV_TYPE(struct ibv_wc)
HIPOBJ_IBV_MEMBER(struct ibv_wc, wr_id)
HIPOBJ_IBV_MEMBER(struct ibv_wc, status)
HIPOBJ_IBV_MEMBER(struct ibv_wc, opcode)
HIPOBJ_IBV_MEMBER(struct ibv_wc, vendor_err)
HIPOBJ_IBV_MEMBER(struct ibv_wc, byte_len)
HIPOBJ_IBV_MEMBER(struct ibv_wc, imm_data)
HIPOBJ_IBV_MEMBER(struct ibv_wc, invalidated_rkey)
HIPOBJ_IBV_MEMBER(struct ibv_wc, qp_num)
HIPOBJ_IBV_MEMBER(struct ibv_wc, src_qp)
HIPOBJ_IBV_MEMBER(struct ibv_wc, wc_flags)
HIPOBJ_IBV_MEMBER(struct ibv_wc, pkey_index)
HIPOBJ_IBV_MEMBER(struct ibv_wc, slid)
HIPOBJ_IBV_MEMBER(struct ibv_wc, sl)
HIPOBJ_IBV_MEMBER(struct ibv_wc, dlid_path_bits)

HIPOBJ_IBV_VALUE(IBV_ACCESS_LOCAL_WRITE)
HIPOBJ_IBV_VALUE(IBV_ACCESS_REMOTE_WRITE)
HIPOBJ_IBV_VALUE(IBV_ACCESS_REMOTE_READ)
HIPOBJ_IBV_VALUE(IBV_ACCESS_REMOTE_ATOMIC)
HIPOBJ_IBV_VALUE(IBV_ACCESS_MW_BIND)
HIPOBJ_IBV_VALUE(IBV_ACCESS_ZERO_BASED)
HIPOBJ_IBV_VALUE(IBV_ACCESS_ON_DEMAND)
HIPOBJ_IBV_VALUE(IBV_ACCESS_HUGETLB)
HIPOBJ_IBV_VALUE(IBV_ACCESS_FLUSH_GLOBAL)
HIPOBJ_IBV_VALUE(IBV_ACCESS_FLUSH_PERSISTENT)
HIPOBJ_IBV_VALUE(IBV_ACCESS_RELAXED_ORDERING)

HIPOBJ_IBV_TYPE(struct ibv_pd)
HIPOBJ_IBV_MEMBER(struct ibv_pd, context)
HIPOBJ_IBV_MEMBER(struct ibv_pd, handle)

HIPOBJ_IBV_TYPE(struct ibv_mr)
HIPOBJ_IBV_MEMBER(struct ibv_mr, context)
HIPOBJ_IBV_MEMBER(struct ibv_mr, pd)
HIPOBJ_IBV_MEMBER(struct ibv_mr, addr)
HIPOBJ_IBV_MEMBER(struct ibv_mr, length)
HIPOBJ_IBV_MEMBER(struct ibv_mr, handle)
HIPOBJ_IBV_MEMBER(struct ibv_mr, lkey)
HIPOBJ_IBV_MEMBER(struct ibv_mr, rkey)

HIPOBJ_IBV_TYPE(struct ibv_global_route)
HIPOBJ_IBV_MEMBER(struct ibv_global_route, dgid)
HIPOBJ_IBV_MEMBER(struct ibv_global_route, flow_label)
HIPOBJ_IBV_MEMBER(struct ibv_global_route, sgid_index)
HIPOBJ_IBV_MEMBER(struct ibv_global_route, hop_limit)
HIPOBJ_IBV_MEMBER(struct ibv_global_route, traffic_class)

HIPOBJ_IBV_TYPE(struct ibv_ah_attr)
HIPOBJ_IBV_MEMBER(struct ibv_ah_attr, grh)
HIPOBJ_IBV_MEMBER(struct ibv_ah_attr, dlid)
HIPOBJ_IBV_MEMBER(struct ibv_ah_attr, sl)
HIPOBJ_IBV_MEMBER(struct ibv_ah_attr, src_path_bits)
HIPOBJ_IBV_MEMBER(struct ibv_ah_attr, static_rate)
HIPOBJ_IBV_MEMBER(struct ibv_ah_attr, is_global)
HIPOBJ_IBV_MEMBER(struct ibv_ah_attr, port_num)

HIPOBJ_IBV_VALUE(IBV_QPT_RC)
HIPOBJ_IBV_VALUE(IBV_QPT_UC)
HIPOBJ_IBV_VALUE(IBV_QPT_UD)
HIPOBJ_IBV_VALUE(IBV_QPT_RAW_PACKET)
HIPOBJ_IBV_VALUE(IBV_QPT_XRC_SEND)
HIPOBJ_IBV_VALUE(IBV_QPT_XRC_RECV)
HIPOBJ_IBV_VALUE(IBV_QPT_DRIVER)

HIPOBJ_IBV_TYPE(struct ibv_qp_cap)
HIPOBJ_IBV_MEMBER(struct ibv_qp_cap, max_send_wr)
HIPOBJ_IBV_MEMBER(struct ibv_qp_cap, max_recv_wr)
HIPOBJ_IBV_MEMBER(struct ibv_qp_cap, max_send_sge)
HIPOBJ_IBV_MEMBER(struct ibv_qp_cap, max_recv_sge)
HIPOBJ_IBV_MEMBER(struct ibv_qp_cap, max_inline_data)

HIPOBJ_IBV_TYPE(struct ibv_qp_init_attr)
HIPOBJ_IBV_MEMBER(struct ibv_qp_init_attr, qp_context)
HIPOBJ_IBV_MEMBER(struct ibv_qp_init_attr, send_cq)
HIPOBJ_IBV_MEMBER(struct ibv_qp_init_attr, recv_cq)
HIPOBJ_IBV_MEMBER(struct ibv_qp_init_attr, srq)
HIPOBJ_IBV_MEMBER(struct ibv_qp_init_attr, cap)
HIPOBJ_IBV_MEMBER(struct ibv_qp_init_attr, qp_type)
HIPOBJ_IBV_MEMBER(struct ibv_qp_init_attr, sq_sig_all)

HIPOBJ_IBV_VALUE(IBV_QP_STATE)
HIPOBJ_IBV_VALUE(IBV_QP_CUR_STATE)
HIPOBJ_IBV_VALUE(IBV_QP_EN_SQD_ASYNC_NOTIFY)
HIPOBJ_IBV_VALUE(IBV_QP_ACCESS_FLAGS)
HIPOBJ_IBV_VALUE(IBV_QP_PKEY_INDEX)
HIPOBJ_IBV_VALUE(IBV_QP_PORT)
HIPOBJ_IBV_VALUE(IBV_QP_QKEY)
HIPOBJ_IBV_VALUE(IBV_QP_AV)
HIPOBJ_IBV_VALUE(IBV_QP_PATH_MTU)
HIPOBJ_IBV_VALUE(IBV_QP_TIMEOUT)
HIPOBJ_IBV_VALUE(IBV_QP_RETRY_CNT)
HIPOBJ_IBV_VALUE(IBV_QP_RNR_RETRY)
HIPOBJ_IBV_VALUE(IBV_QP_RQ_PSN)
HIPOBJ_IBV_VALUE(IBV_QP_MAX_QP_RD_ATOMIC)
HIPOBJ_IBV_VALUE(IBV_QP_ALT_PATH)
HIPOBJ_IBV_VALUE(IBV_QP_MIN_RNR_TIMER)
HIPOBJ_IBV_VALUE(IBV_QP_SQ_PSN)
HIPOBJ_IBV_VALUE(IBV_QP_MAX_DEST_RD_ATOMIC)
HIPOBJ_IBV_VALUE(IBV_QP_PATH_MIG_STATE)
HIPOBJ_IBV_VALUE(IBV_QP_CAP)
HIPOBJ_IBV_VALUE(IBV_QP_DEST_QPN)
HIPOBJ_IBV_VALUE(IBV_QP_RATE_LIMIT)

HIPOBJ_IBV_VALUE(IBV_QPS_RESET)
HIPOBJ_IBV_VALUE(IBV_QPS_INIT)
HIPOBJ_IBV_VALUE(IBV_QPS_RTR)
HIPOBJ_IBV_VALUE(IBV_QPS_RTS)
HIPOBJ_IBV_VALUE(IBV_QPS_SQD)
HIPOBJ_IBV_VALUE(IBV_QPS_SQE)
HIPOBJ_IBV_VALUE(IBV_QPS_ERR)
HIPOBJ_IBV_VALUE(IBV_QPS_UNKNOWN)

HIPOBJ_IBV_VALUE(IBV_MIG_MIGRATED)
HIPOBJ_IBV_VALUE(IBV_MIG_REARM)
HIPOBJ_IBV_VALUE(IBV_MIG_ARMED)

HIPOBJ_IBV_TYPE(struct ibv_qp_attr)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, qp_state)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, cur_qp_state)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, path_mtu)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, path_mig_state)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, qkey)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, rq_psn)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, sq_psn)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, dest_qp_num)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, qp_access_flags)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, cap)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, ah_attr)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, alt_ah_attr)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, pkey_index)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, alt_pkey_index)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, en_sqd_async_notify)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, sq_draining)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, max_rd_atomic)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, max_dest_rd_atomic)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, min_rnr_timer)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, port_num)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, timeout)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, retry_cnt)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, rnr_retry)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, alt_port_num)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, alt_timeout)
HIPOBJ_IBV_MEMBER(struct ibv_qp_attr, rate_limit)

HIPOBJ_IBV_TYPE(struct ibv_qp)
HIPOBJ_IBV_MEMBER(struct ibv_qp, context)
HIPOBJ_IBV_MEMBER(struct ibv_qp, qp_context)
HIPOBJ_IBV_MEMBER(struct ibv_qp, pd)
HIPOBJ_IBV_MEMBER(struct ibv_qp, send_cq)
HIPOBJ_IBV_MEMBER(struct ibv_qp, recv_cq)
HIPOBJ_IBV_MEMBER(struct ibv_qp, srq)
HIPOBJ_IBV_MEMBER(struct ibv_qp, handle)
HIPOBJ_IBV_MEMBER(struct ibv_qp, qp_num)
HIPOBJ_IBV_MEMBER(struct ibv_qp, state)
HIPOBJ_IBV_MEMBER(struct ibv_qp, qp_type)
HIPOBJ_IBV_MEMBER(struct ibv_qp, mutex)
HIPOBJ_IBV_MEMBER(struct ibv_qp, cond)
HIPOBJ_IBV_MEMBER(struct ibv_qp, events_completed)

HIPOBJ_IBV_VALUE(IBV_WR_RDMA_WRITE)
HIPOBJ_IBV_VALUE(IBV_WR_RDMA_WRITE_WITH_IMM)
HIPOBJ_IBV_VALUE(IBV_WR_SEND)
HIPOBJ_IBV_VALUE(IBV_WR_SEND_WITH_IMM)
HIPOBJ_IBV_VALUE(IBV_WR_RDMA_READ)
HIPOBJ_IBV_VALUE(IBV_WR_ATOMIC_CMP_AND_SWP)
HIPOBJ_IBV_VALUE(IBV_WR_ATOMIC_FETCH_AND_ADD)
HIPOBJ_IBV_VALUE(IBV_WR_LOCAL_INV)
HIPOBJ_IBV_VALUE(IBV_WR_BIND_MW)
HIPOBJ_IBV_VALUE(IBV_WR_SEND_WITH_INV)
HIPOBJ_IBV_VALUE(IBV_WR_TSO)
HIPOBJ_IBV_VALUE(IBV_WR_DRIVER1)
HIPOBJ_IBV_VALUE(IBV_WR_FLUSH)
HIPOBJ_IBV_VALUE(IBV_WR_ATOMIC_WRITE)

HIPOBJ_IBV_VALUE(IBV_SEND_FENCE)
HIPOBJ_IBV_VALUE(IBV_SEND_SIGNALED)
HIPOBJ_IBV_VALUE(IBV_SEND_SOLICITED)
HIPOBJ_IBV_VALUE(IBV_SEND_INLINE)

HIPOBJ_IBV_TYPE(struct ibv_sge)
HIPOBJ_IBV_MEMBER(struct ibv_sge, addr)
HIPOBJ_IBV_MEMBER(struct ibv_sge, length)
HIPOBJ_IBV_MEMBER(struct ibv_sge, lkey)

HIPOBJ_IBV_TYPE(struct ibv_mw_bind_info)
HIPOBJ_IBV_MEMBER(struct ibv_mw_bind_info, mr)
HIPOBJ_IBV_MEMBER(struct ibv_mw_bind_info, addr)
HIPOBJ_IBV_MEMBER(struct ibv_mw_bind_info, length)
HIPOBJ_IBV_MEMBER(struct ibv_mw_bind_info, mw_access_flags)

HIPOBJ_IBV_TYPE(struct ibv_send_wr)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr_id)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, next)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, sg_list)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, num_sge)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, opcode)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, send_flags)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, imm_data)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, invalidate_rkey)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.rdma)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.rdma.remote_addr)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.rdma.rkey)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.atomic)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.atomic.remote_addr)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.atomic.compare_add)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.atomic.swap)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.atomic.rkey)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.ud)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.ud.ah)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.ud.remote_qpn)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, wr.ud.remote_qkey)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, qp_type)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, qp_type.xrc)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, qp_type.xrc.remote_srqn)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, bind_mw)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, bind_mw.mw)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, bind_mw.rkey)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, bind_mw.bind_info)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, tso)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, tso.hdr)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, tso.hdr_sz)
HIPOBJ_IBV_MEMBER(struct ibv_send_wr, tso.mss)

HIPOBJ_IBV_TYPE(struct ibv_recv_wr)
HIPOBJ_IBV_MEMBER(struct ibv_recv_wr, wr_id)
HIPOBJ_IBV_MEMBER(struct ibv_recv_wr, next)
HIPOBJ_IBV_MEMBER(struct ibv_recv_wr, sg_list)
HIPOBJ_IBV_MEMBER(struct ibv_recv_wr, num_sge)

HIPOBJ_IBV_VALUE(IBV_SYSFS_NAME_MAX)
HIPOBJ_IBV_VALUE(IBV_SYSFS_PATH_MAX)

HIPOBJ_IBV_TYPE(struct ibv_device)
HIPOBJ_IBV_MEMBER(struct ibv_device, _ops)
HIPOBJ_IBV_MEMBER(struct ibv_device, _ops._dummy1)
HIPOBJ_IBV_MEMBER(struct ibv_device, _ops._dummy2)
HIPOBJ_IBV_MEMBER(struct ibv_device, node_type)
HIPOBJ_IBV_MEMBER(struct ibv_device, transport_type)
HIPOBJ_IBV_MEMBER(struct ibv_device, name)
HIPOBJ_IBV_MEMBER(struct ibv_device, dev_name)
HIPOBJ_IBV_MEMBER(struct ibv_device, dev_path)
HIPOBJ_IBV_MEMBER(struct ibv_device, ibdev_path)

HIPOBJ_IBV_TYPE(struct ibv_comp_channel)
HIPOBJ_IBV_MEMBER(struct ibv_comp_channel, context)
HIPOBJ_IBV_MEMBER(struct ibv_comp_channel, fd)
HIPOBJ_IBV_MEMBER(struct ibv_comp_channel, refcnt)

HIPOBJ_IBV_TYPE(struct ibv_srq)
HIPOBJ_IBV_MEMBER(struct ibv_srq, context)
HIPOBJ_IBV_MEMBER(struct ibv_srq, srq_context)
HIPOBJ_IBV_MEMBER(struct ibv_srq, pd)
HIPOBJ_IBV_MEMBER(struct ibv_srq, handle)
HIPOBJ_IBV_MEMBER(struct ibv_srq, mutex)
HIPOBJ_IBV_MEMBER(struct ibv_srq, cond)
HIPOBJ_IBV_MEMBER(struct ibv_srq, events_completed)

HIPOBJ_IBV_TYPE(struct ibv_cq)
HIPOBJ_IBV_MEMBER(struct ibv_cq, context)
HIPOBJ_IBV_MEMBER(struct ibv_cq, channel)
HIPOBJ_IBV_MEMBER(struct ibv_cq, cq_context)
HIPOBJ_IBV_MEMBER(struct ibv_cq, handle)
HIPOBJ_IBV_MEMBER(struct ibv_cq, cqe)
HIPOBJ_IBV_MEMBER(struct ibv_cq, mutex)
HIPOBJ_IBV_MEMBER(struct ibv_cq, cond)
HIPOBJ_IBV_MEMBER(struct ibv_cq, comp_events_completed)
HIPOBJ_IBV_MEMBER(struct ibv_cq, async_events_completed)

HIPOBJ_IBV_TYPE(struct ibv_context_ops)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_query_device)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_query_port)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_alloc_pd)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_dealloc_pd)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_reg_mr)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_rereg_mr)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_dereg_mr)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, alloc_mw)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, bind_mw)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, dealloc_mw)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_create_cq)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, poll_cq)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, req_notify_cq)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_cq_event)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_resize_cq)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_destroy_cq)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_create_srq)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_modify_srq)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_query_srq)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_destroy_srq)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, post_srq_recv)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_create_qp)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_query_qp)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_modify_qp)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_destroy_qp)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, post_send)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, post_recv)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_create_ah)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_destroy_ah)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_attach_mcast)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_detach_mcast)
HIPOBJ_IBV_MEMBER(struct ibv_context_ops, _compat_async_event)

HIPOBJ_IBV_TYPE(struct ibv_context)
HIPOBJ_IBV_MEMBER(struct ibv_context, device)
HIPOBJ_IBV_MEMBER(struct ibv_context, ops)
HIPOBJ_IBV_MEMBER(struct ibv_context, cmd_fd)
HIPOBJ_IBV_MEMBER(struct ibv_context, async_fd)
HIPOBJ_IBV_MEMBER(struct ibv_context, num_comp_vectors)
HIPOBJ_IBV_MEMBER(struct ibv_context, mutex)
HIPOBJ_IBV_MEMBER(struct ibv_context, abi_compat)
